// data.jsx — mock data for the course builder prototype.
// Lesson type vocabulary, sample course outline, template library, i18n strings.

const LESSON_TYPES = [
  { id: 'content',      icon: 'book',        labelEn: 'Reading',         labelEs: 'Lectura',          descEn: 'Rich-text content with images and embeds.',     descEs: 'Contenido con texto enriquecido e imágenes.' },
  { id: 'video',        icon: 'play',        labelEn: 'Video',           labelEs: 'Video',            descEn: 'Hosted or embedded video lesson.',              descEs: 'Lección de video alojada o embebida.' },
  { id: 'audio',        icon: 'music',       labelEn: 'Audio',           labelEs: 'Audio',            descEn: 'Podcast-style audio with transcript.',          descEs: 'Audio estilo podcast con transcripción.' },
  { id: 'pdf',          icon: 'file',        labelEn: 'PDF',             labelEs: 'PDF',              descEn: 'Downloadable document with viewer.',            descEs: 'Documento descargable con visor.' },
  { id: 'project',      icon: 'clipboard',   labelEn: 'Project',         labelEs: 'Proyecto',         descEn: 'Assignment with student submission + review.',  descEs: 'Tarea con entrega y revisión.' },
  { id: 'exam',         icon: 'quiz',        labelEn: 'Quiz',            labelEs: 'Examen',           descEn: 'Auto-graded questions with time limit.',        descEs: 'Preguntas evaluadas con límite de tiempo.' },
  { id: 'live',         icon: 'calendar',    labelEn: 'Live session',    labelEs: 'Sesión en vivo',   descEn: 'Scheduled consultancy or workshop.',            descEs: 'Consultoría o taller programado.' },
  { id: 'external',     icon: 'link',        labelEn: 'External link',   labelEs: 'Enlace externo',   descEn: 'URL or embedded iframe.',                       descEs: 'URL o iframe embebido.' },
  { id: 'interactive',  icon: 'cube',        labelEn: 'Interactive',     labelEs: 'Interactivo',      descEn: 'Drag-and-drop, code sandbox, simulators.',      descEs: 'Arrastrar y soltar, code sandbox, simuladores.' },
  { id: 'scorm',        icon: 'layers',      labelEn: 'SCORM / xAPI',    labelEs: 'SCORM / xAPI',     descEn: 'Imported learning package.',                    descEs: 'Paquete de aprendizaje importado.' },
];

const LESSON_TYPE_BY_ID = Object.fromEntries(LESSON_TYPES.map(t => [t.id, t]));

// Sample generated outline used as the starting course state after AI creation
const SAMPLE_COURSE = {
  title: 'Advanced React Patterns',
  description: 'A four-week deep-dive into modern React: compound components, render props, Suspense, and the latest server-component patterns. Built for engineers who already know hooks and want to ship maintainable production apps.',
  category: 'Engineering',
  level: 'Intermediate',
  language: 'English',
  duration: '4 weeks',
  cover: null,
  published: false,
  modules: [
    {
      id: 'm1', title: 'Foundations & mental model',
      description: 'Why patterns matter — composition, ownership, and the cost of abstraction.',
      lessons: [
        { id: 'l1', type: 'video',   title: 'Course welcome', duration: '04:30', status: 'ready' },
        { id: 'l2', type: 'content', title: 'How to think in components', duration: '12 min read', status: 'ready' },
        { id: 'l3', type: 'video',   title: 'Composition over configuration', duration: '18:20', status: 'ready' },
        { id: 'l4', type: 'exam',    title: 'Module quiz', duration: '10 min', status: 'draft' },
      ],
    },
    {
      id: 'm2', title: 'Compound components',
      description: 'Building flexible APIs with implicit shared state.',
      lessons: [
        { id: 'l5', type: 'video',   title: 'Tabs from scratch',         duration: '22:10', status: 'ready' },
        { id: 'l6', type: 'content', title: 'Context vs. cloneElement',  duration: '8 min read', status: 'ready' },
        { id: 'l7', type: 'project', title: 'Build an Accordion',         duration: '90 min', status: 'ready' },
      ],
    },
    {
      id: 'm3', title: 'Suspense & data',
      description: 'Streaming, error boundaries, and avoiding waterfalls.',
      lessons: [
        { id: 'l8',  type: 'video',     title: 'The Suspense mental model', duration: '16:45', status: 'ready' },
        { id: 'l9',  type: 'content',   title: 'Reading patterns',          duration: '14 min read', status: 'empty' },
        { id: 'l10', type: 'interactive', title: 'Sandbox: streaming list', duration: '30 min', status: 'empty' },
      ],
    },
    {
      id: 'm4', title: 'Server components in production',
      description: 'Boundaries, caching, and the new rendering model.',
      lessons: [
        { id: 'l11', type: 'video',    title: 'RSC fundamentals',     duration: '24:00', status: 'empty' },
        { id: 'l12', type: 'external', title: 'Vercel reference app', duration: 'External', status: 'ready' },
        { id: 'l13', type: 'project',  title: 'Capstone build',       duration: '6 hrs',  status: 'empty' },
        { id: 'l14', type: 'live',     title: 'Office hours Q&A',     duration: '60 min', status: 'scheduled' },
      ],
    },
  ],
};

// AI prompt suggestion chips
const PROMPT_CHIPS = [
  '4-week intro to product management for new hires',
  'Mini cohort on data viz with Python and Plotly',
  'Customer-success onboarding, 6 short lessons',
  'Sales fundamentals for SDRs, with role-play',
];

// Template library cards
const TEMPLATES = [
  { id: 't1', name: '4-week bootcamp',     meta: '4 modules · 18 lessons',  desc: 'Weekly cadence with projects + checkpoint quizzes.', tag: 'Cohort' },
  { id: 't2', name: 'Mini cohort (2 wks)', meta: '2 modules · 8 lessons',   desc: 'Compact format. Good for executive education.',      tag: 'Cohort' },
  { id: 't3', name: 'Self-paced library',  meta: 'No cohort · open enrollment', desc: 'Evergreen content, no due dates.',               tag: 'Self-paced' },
  { id: 't4', name: 'Onboarding track',    meta: '3 modules · 12 lessons',  desc: 'New-hire ramp with role-specific branches.',         tag: 'Internal' },
  { id: 't5', name: 'Certificate prep',    meta: '5 modules · 24 lessons',  desc: 'Exam-heavy, with practice tests + retakes.',         tag: 'Exam-led' },
  { id: 't6', name: 'Workshop one-off',    meta: '1 module · 3 lessons',    desc: 'Single live session + pre-read + post-work.',        tag: 'Workshop' },
];

// Existing courses available to duplicate
const EXISTING_COURSES = [
  { id: 'c1', name: 'Intro to React',          meta: '3 modules · 12 lessons', updated: '2 days ago' },
  { id: 'c2', name: 'SQL for Course Operators', meta: '5 modules · 22 lessons', updated: '1 week ago' },
  { id: 'c3', name: 'Design Systems in Practice', meta: '4 modules · 16 lessons', updated: '3 weeks ago' },
];

// Tiny i18n helper — flat dict keyed by string id.
const I18N = {
  en: {
    'app.brand': 'SkillsRamp',
    'crumb.courses': 'Courses',
    'btn.publish': 'Publish',
    'btn.unpublish': 'Unpublish',
    'btn.preview': 'Preview',
    'btn.invite': 'Invite reviewers',
    'btn.save': 'Save',
    'btn.cancel': 'Cancel',
    'btn.delete': 'Delete',
    'btn.duplicate': 'Duplicate',
    'btn.addModule': 'Add module',
    'btn.addLesson': 'Add lesson',
    'btn.newCourse': 'New course',
    'btn.startBuilding': 'Start building',
    'btn.refine': 'Refine outline',
    'btn.generate': 'Generate outline',
    'btn.regenerate': 'Regenerate',
    'btn.accept': 'Accept & continue',
    'btn.back': 'Back',

    'home.eyebrow': '2026 · Q2 · WEEK 21',
    'home.title': 'Courses',
    'home.subtitle': 'Build, ship, and iterate on what your tenants learn.',
    'home.empty.title': 'No courses yet — start one',
    'home.empty.body': 'Describe what you want to teach and we\u2019ll draft an outline you can edit. Or start from a blank canvas.',
    'home.empty.ai': 'Generate with AI',
    'home.empty.blank': 'Start blank',
    'home.empty.browse': 'Browse templates',

    'create.title': 'New course',
    'create.tab.ai': 'Generate with AI',
    'create.tab.blank': 'Blank',
    'create.tab.duplicate': 'Duplicate',
    'create.tab.template': 'Template',
    'create.ai.label': 'Describe your course in a sentence',
    'create.ai.placeholder': 'e.g. A four-week deep-dive into modern React for engineers who know hooks…',
    'create.ai.hint': 'Mention duration, audience, and level for the best draft.',
    'create.ai.suggestions': 'Or try one of these:',
    'create.blank.label': 'Course title',
    'create.review.eyebrow': 'AI draft · review and refine',
    'create.review.title': 'Here\u2019s the outline',
    'create.review.modules': 'Modules',
    'create.review.lessons': 'lessons',

    'builder.tab.curriculum': 'Curriculum',
    'builder.tab.settings': 'Settings',
    'builder.tab.outcomes': 'Outcomes',
    'builder.tab.pricing': 'Pricing',
    'builder.curriculum.heading': 'Curriculum',
    'builder.curriculum.empty.title': 'Empty curriculum',
    'builder.curriculum.empty.body': 'Add your first module or have AI draft an outline from a one-line brief.',
    'builder.inspect': 'Inspector',
    'builder.fields.title': 'Course title',
    'builder.fields.description': 'Short description',
    'builder.fields.category': 'Category',
    'builder.fields.language': 'Language',
    'builder.fields.level': 'Level',
    'builder.fields.duration': 'Duration',
    'builder.fields.cover': 'Cover image',
    'builder.fields.cover.hint': 'PNG or JPG, 16:9 ratio. Auto-generated covers available.',
    'builder.cover.generate': 'Generate cover',
    'builder.save.saved': 'All changes saved',
    'builder.save.saving': 'Saving\u2026',
    'builder.save.idle': 'Autosaving every change',

    'lesson.title': 'Lesson title',
    'lesson.type': 'Lesson type',
    'lesson.duration': 'Estimated time',
    'lesson.visibility': 'Visibility',
    'lesson.body': 'Lesson body',
    'lesson.body.empty': 'Start writing, or generate from a prompt\u2026',
    'lesson.ai.body': 'Draft body',
    'lesson.ai.quiz': 'Generate quiz',
    'lesson.ai.outline': 'Outline this lesson',
    'lesson.preview': 'Preview lesson',

    'publish.title': 'Ready to publish?',
    'publish.subtitle': 'A quick preflight before students see this course.',
    'publish.visibility.title': 'Visibility',
    'publish.visibility.public': 'Public — listed in the catalog',
    'publish.visibility.tenant': 'Tenant only — Acme University signed-in users',
    'publish.visibility.unlisted': 'Unlisted — direct link only',
    'publish.cta': 'Publish now',
    'publish.schedule': 'Schedule\u2026',
    'publish.checks': 'Preflight',

    'status.draft': 'Draft',
    'status.published': 'Published',
    'status.scheduled': 'Scheduled',
    'status.ready': 'Ready',
    'status.empty': 'Empty',
  },
  es: {
    'app.brand': 'SkillsRamp',
    'crumb.courses': 'Cursos',
    'btn.publish': 'Publicar',
    'btn.unpublish': 'Despublicar',
    'btn.preview': 'Vista previa',
    'btn.invite': 'Invitar revisores',
    'btn.save': 'Guardar',
    'btn.cancel': 'Cancelar',
    'btn.delete': 'Eliminar',
    'btn.duplicate': 'Duplicar',
    'btn.addModule': 'Añadir módulo',
    'btn.addLesson': 'Añadir lección',
    'btn.newCourse': 'Nuevo curso',
    'btn.startBuilding': 'Empezar a construir',
    'btn.refine': 'Refinar esquema',
    'btn.generate': 'Generar esquema',
    'btn.regenerate': 'Regenerar',
    'btn.accept': 'Aceptar y continuar',
    'btn.back': 'Volver',

    'home.eyebrow': '2026 · Q2 · SEMANA 21',
    'home.title': 'Cursos',
    'home.subtitle': 'Crea, publica e itera sobre lo que aprenden tus tenants.',
    'home.empty.title': 'Aún no hay cursos \u2014 empieza uno',
    'home.empty.body': 'Describe lo que quieres enseñar y redactamos un esquema editable. O empieza desde cero.',
    'home.empty.ai': 'Generar con IA',
    'home.empty.blank': 'Empezar en blanco',
    'home.empty.browse': 'Ver plantillas',

    'create.title': 'Nuevo curso',
    'create.tab.ai': 'Generar con IA',
    'create.tab.blank': 'En blanco',
    'create.tab.duplicate': 'Duplicar',
    'create.tab.template': 'Plantilla',
    'create.ai.label': 'Describe tu curso en una frase',
    'create.ai.placeholder': 'ej. Curso intensivo de React de cuatro semanas para ingenieros con experiencia en hooks\u2026',
    'create.ai.hint': 'Menciona duración, audiencia y nivel para mejores resultados.',
    'create.ai.suggestions': 'O prueba una de estas:',
    'create.blank.label': 'Título del curso',
    'create.review.eyebrow': 'Borrador IA · revisar y refinar',
    'create.review.title': 'Aquí está el esquema',
    'create.review.modules': 'Módulos',
    'create.review.lessons': 'lecciones',

    'builder.tab.curriculum': 'Currículum',
    'builder.tab.settings': 'Ajustes',
    'builder.tab.outcomes': 'Resultados',
    'builder.tab.pricing': 'Precio',
    'builder.curriculum.heading': 'Currículum',
    'builder.curriculum.empty.title': 'Currículum vacío',
    'builder.curriculum.empty.body': 'Añade tu primer módulo o pide a la IA que redacte un esquema.',
    'builder.inspect': 'Inspector',
    'builder.fields.title': 'Título del curso',
    'builder.fields.description': 'Descripción corta',
    'builder.fields.category': 'Categoría',
    'builder.fields.language': 'Idioma',
    'builder.fields.level': 'Nivel',
    'builder.fields.duration': 'Duración',
    'builder.fields.cover': 'Imagen de portada',
    'builder.fields.cover.hint': 'PNG o JPG, proporción 16:9. Portadas auto-generadas disponibles.',
    'builder.cover.generate': 'Generar portada',
    'builder.save.saved': 'Todos los cambios guardados',
    'builder.save.saving': 'Guardando\u2026',
    'builder.save.idle': 'Autoguardado activo',

    'lesson.title': 'Título de la lección',
    'lesson.type': 'Tipo de lección',
    'lesson.duration': 'Tiempo estimado',
    'lesson.visibility': 'Visibilidad',
    'lesson.body': 'Contenido de la lección',
    'lesson.body.empty': 'Empieza a escribir, o genera desde un prompt\u2026',
    'lesson.ai.body': 'Borrador',
    'lesson.ai.quiz': 'Generar examen',
    'lesson.ai.outline': 'Esquema de esta lección',
    'lesson.preview': 'Vista previa',

    'publish.title': '¿Listo para publicar?',
    'publish.subtitle': 'Una verificación rápida antes de que los estudiantes vean el curso.',
    'publish.visibility.title': 'Visibilidad',
    'publish.visibility.public': 'Público \u2014 listado en el catálogo',
    'publish.visibility.tenant': 'Solo tenant \u2014 usuarios de Acme University',
    'publish.visibility.unlisted': 'No listado \u2014 solo enlace directo',
    'publish.cta': 'Publicar ahora',
    'publish.schedule': 'Programar\u2026',
    'publish.checks': 'Comprobaciones',

    'status.draft': 'Borrador',
    'status.published': 'Publicado',
    'status.scheduled': 'Programado',
    'status.ready': 'Listo',
    'status.empty': 'Vacío',
  },
};

function useT(lang) {
  return React.useCallback((key) => (I18N[lang] || I18N.en)[key] || key, [lang]);
}

Object.assign(window, {
  LESSON_TYPES, LESSON_TYPE_BY_ID,
  SAMPLE_COURSE, PROMPT_CHIPS, TEMPLATES, EXISTING_COURSES,
  I18N, useT,
});
